[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coxmunk"
dynamic = ["version"]
description = "simple sunglint computation based on Cox-Munk wave slope distribution"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "T. Harmel", email = "tristan.harmel@gmail.com" }]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "xarray",
    "netCDF4",
    "matplotlib",
    "cmocean",
    "docopt",
]

[project.urls]
Homepage = "https://github.com/Tristanovsk/coxmunk"

[project.scripts]
coxmunk = "coxmunk.visu:main"

[tool.setuptools]
packages = ["coxmunk"]

[tool.setuptools.dynamic]
version = { attr = "coxmunk.__version__" }
